"""Welcome / documentation page for the HPLC / GC-MS pipeline GUI."""

from __future__ import annotations

import pandas as pd
import streamlit as st

st.title("HPLC / GC-MS pipeline")
st.caption(
    "Batch-process Agilent .D injections → calibrated concentrations → interactive dashboards"
)

tab_start, tab_folder, tab_naming, tab_pipeline, tab_params, tab_results = st.tabs([
    "Quick start",
    "Folder & files",
    "Sample naming",
    "How it works",
    "Parameters",
    "Results",
])


# ── Quick start ───────────────────────────────────────────────────────────────
with tab_start:
    st.subheader("What this tool does")
    st.markdown(
        "This pipeline takes raw **Agilent .D injection folders** from an HPLC or GC-MS run, "
        "integrates peaks, applies a calibration curve, and produces **interactive Bokeh dashboards** "
        "showing compound concentrations across strains and time points. "
        "Both HPLC (UV/DAD detector) and GC-MS can run in the same experiment."
    )

    st.subheader("Workflow at a glance")
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        with st.container(border=True):
            st.markdown(":material/folder_open: **1 · Load**")
            st.caption(
                "Click **Browse for folder** in the sidebar and pick your experiment folder. "
                "Or paste the path directly into the text box and click **Load**."
            )
    with col2:
        with st.container(border=True):
            st.markdown(":material/tune: **2 · Configure**")
            st.caption(
                "Review **Parameters**: set your detection wavelength, define compound RT windows "
                "in `compounds.csv`, and supply calibration data in `standard.csv`."
            )
    with col3:
        with st.container(border=True):
            st.markdown(":material/auto_awesome: **3 · Initialize**")
            st.caption(
                "Open the **Initialize** page in the sidebar. For GC-MS and HPLC + GC, "
                "it scans your .D files and auto-detects peaks. For HPLC-only, it writes "
                "a template config to fill in."
            )
    with col4:
        with st.container(border=True):
            st.markdown(":material/play_arrow: **4 · Run & explore**")
            st.caption(
                "Click **Run both** on the Run page to process all injections. "
                "Results appear under **Results** in the sidebar as interactive HTML dashboards."
            )

    st.divider()
    st.subheader("View mode vs. Edit mode")
    st.markdown(
        "The sidebar has an **Edit mode** toggle (visible after loading a folder). "
        "When off (the default for experiments that already have results), all parameters "
        "are read-only and action buttons are disabled — safe for exploring results without "
        "accidentally changing anything. Toggle it on to edit parameters, initialize, and re-run."
    )

    st.divider()
    st.subheader("Returning to an existing experiment")
    st.markdown(
        "Just load the folder — the pipeline reads your existing `hplc_config.yaml`, "
        "`compounds.csv`, and `standard.csv` automatically. "
        "Results pages become available immediately if the pipeline has already been run."
    )


# ── Folder & files ─────────────────────────────────────────────────────────────
with tab_folder:
    st.subheader("Experiment folder layout")
    st.markdown(
        "All files — raw data, config, CSVs, and outputs — live under one **experiment folder**. "
        "You can name it anything. The layout below is typical; raw .D folders can sit at the "
        "root or in a subfolder (set `data_dir` in Parameters)."
    )

    st.code(
        """\
my_experiment/
│
│  ── Configuration & reference files (you provide these) ──────────────────
├── hplc_config.yaml          ← auto-generated by Initialize; edit in Parameters
├── compounds.csv             ← HPLC compounds: name + retention-time window
├── standard.csv              ← HPLC calibration: (area, concentration) pairs
├── gc_compounds.csv          ← GC-MS compounds: name + RT + quantifier m/z
│
│  ── Raw HPLC injections (.D folders) ─────────────────────────────────────
├── Data/                     ← set data_dir = "Data" in Parameters
│   ├── 0, media, A.D
│   ├── 0, media, B.D
│   ├── 24, s1, A.D
│   ├── 24, s1, B.D
│   ├── 24, s1, C.D
│   └── blank.D               ← set blank_folder_name = "blank.D"
│
│  ── Raw GC-MS injections (.D folders) ────────────────────────────────────
├── GC_Data/                  ← set gc → data_dir = "GC_Data" in Parameters
│   ├── 0_media_A.D
│   ├── 24_s1_A.D
│   ├── 250uM_34DMS_hexane.D  ← GC-MS calibration standard
│   └── ...
│
│  ── Outputs (created automatically by the pipeline) ──────────────────────
├── results/                  ← Stage 1 HPLC outputs
├── analysis/                 ← Stage 2 HPLC outputs  (Bokeh dashboard here)
├── gc_results/               ← Stage 1 GC-MS outputs
├── gc_analysis/              ← Stage 2 GC-MS outputs (Bokeh dashboard here)
├── combined_analysis/        ← Combined HPLC + GC-MS dashboard
└── logs/                     ← Run logs with timestamps
""",
        language="text",
    )

    st.subheader("Reference files you need to prepare")

    with st.expander("`compounds.csv` — HPLC retention-time windows", icon=":material/table:"):
        st.markdown(
            "Defines the **RT window** [RT_low, RT_high] for each compound. "
            "The pipeline assigns any peak whose RT falls within this window to that compound. "
            "Windows must not overlap. Units are **minutes**."
        )
        st.dataframe(
            pd.DataFrame({
                "Compound": ["pCA", "CA", "FA", "34DMS"],
                "RT_low":   [6.5,   4.9,  6.8,  12.4],
                "RT_high":  [6.6,   5.1,  6.9,  12.6],
                "Notes":    ["",    "",   "",   ""],
            }),
            hide_index=True,
        )
        st.caption(
            "Tip: run Stage 1 once first — it writes `results/peak_results.csv` with all detected "
            "peak RTs, which you can use to set accurate windows."
        )

    with st.expander("`standard.csv` — HPLC calibration data", icon=":material/table:"):
        st.markdown(
            "Each row is one standard injection data point: the integrated **area** of the "
            "compound peak and the **known concentration** (µM). "
            "The pipeline fits a linear regression (area = slope × conc) per compound."
        )
        st.dataframe(
            pd.DataFrame({
                "Compound":      ["pCA",  "pCA",  "pCA",   "pCA",   "CA",  "CA",   "CA"],
                "Area_Integral": [341.8,  720.3,  1933.2,  3856.9,  568.0, 1587.0, 3320.0],
                "concentration": [50,     100,    250,     500,     100,   250,    500],
            }),
            hide_index=True,
        )
        st.caption(
            "You need at least 3 concentration points per compound for a reliable fit. "
            "Integrate these from your pure standard runs by hand (e.g., in OpenChrom or ChemStation) "
            "and paste the values here."
        )

    with st.expander("`gc_compounds.csv` — GC-MS compound definitions", icon=":material/table:"):
        st.markdown(
            "For each GC-MS compound: retention-time window, **quantifier m/z** (the most "
            "selective ion, used for quantification), optional **qualifier m/z** ions "
            "(for identity confirmation), and which compound's calibration standards to use."
        )
        st.dataframe(
            pd.DataFrame({
                "Compound":      ["34DMS"],
                "RT_low":        [12.2],
                "RT_high":       [12.75],
                "quantifier_mz": [164],
                "qualifier_mz":  ["149=0.40;91=0.36"],
                "ion_ratio_tol": [0.30],
                "calibrate_as":  [""],
                "Notes":         ["3-4-dimethoxystyrene"],
            }),
            hide_index=True,
        )
        st.caption(
            "`qualifier_mz` format: `m/z=expected_ratio;...` — the ratio of each qualifier ion "
            "to the quantifier ion. `ion_ratio_tol` = relative tolerance (0.30 = ±30%). "
            "`calibrate_as` = use another compound's standard curve (leave blank to use own)."
        )
        st.info(
            "For GC-MS experiments, use the **Initialize** page — it auto-detects peaks "
            "and quantifier ions from your standard injections and writes a starter `gc_compounds.csv`.",
            icon=":material/auto_awesome:",
        )


# ── Sample naming ─────────────────────────────────────────────────────────────
with tab_naming:
    st.subheader("How to name your .D injection folders")
    st.markdown(
        "The pipeline parses injection names using a **regex with named groups** to extract "
        "three fields: `time` (hours), `strain` (sample identity), and `replicate` (letter). "
        "The default patterns cover common conventions; you can change them in Parameters → "
        "Advanced settings."
    )

    col_hplc, col_gc = st.columns(2)

    with col_hplc:
        with st.container(border=True):
            st.markdown("**HPLC — default pattern**")
            st.code('`<time>, <strain>, <replicate>`', language="text")
            st.caption("Comma + space separated")
            st.markdown("**Examples:**")
            st.code(
                "0, media, A.D     → time=0h,  strain=media, replicate=A\n"
                "24, s1, A.D       → time=24h, strain=s1,    replicate=A\n"
                "24, s1, B.D       → time=24h, strain=s1,    replicate=B\n"
                "50, s11, C.D      → time=50h, strain=s11,   replicate=C",
                language="text",
            )

    with col_gc:
        with st.container(border=True):
            st.markdown("**GC-MS samples — default pattern**")
            st.code('`<time>_<strain>_<replicate>`', language="text")
            st.caption("Underscore separated")
            st.markdown("**Examples:**")
            st.code(
                "0_media_A.D       → time=0h,  strain=media, replicate=A\n"
                "24_s1_A.D         → time=24h, strain=s1,    replicate=A\n"
                "50_s11_C.D        → time=50h, strain=s11,   replicate=C",
                language="text",
            )

    st.divider()
    with st.container(border=True):
        st.markdown("**GC-MS calibration standards — default pattern**")
        st.code('`<conc><unit>_<compound>_<anything>.D`', language="text")
        st.markdown("**Examples:**")
        st.code(
            "250uM_34DMS_hexane.D    → 250 µM standard for compound 34DMS\n"
            "100uM_34DMS_hexane.D    → 100 µM standard for compound 34DMS\n"
            "50uM_34DMS.D            → 50 µM standard",
            language="text",
        )
        st.caption(
            "The compound name in the standard file name must match the `Compound` column in "
            "`gc_compounds.csv` exactly (case-insensitive). The unit can be `uM`, `µM`, `mM`, etc."
        )

    st.divider()
    st.subheader("Custom patterns")
    st.markdown(
        "If your naming convention differs, change the regex in **Parameters → Advanced GC settings** "
        "(or the HPLC section). The pattern must define three named groups:"
    )
    c1, c2, c3 = st.columns(3)
    c1.metric("Group", "`time`")
    c1.caption("Integer — hours. Example: `24`")
    c2.metric("Group", "`strain`")
    c2.caption("Any text — sample ID. Example: `s11`")
    c3.metric("Group", "`replicate`")
    c3.caption("Single letter — biological replicate. Example: `A`")

    st.info(
        "Injection folders that don't match the pattern are **skipped** silently. "
        "If your results seem to have fewer samples than expected, check the pattern "
        "and run a quick test: paste your folder name into a regex tester with the pattern "
        "from Parameters.",
        icon=":material/info:",
    )


# ── How it works ───────────────────────────────────────────────────────────────
with tab_pipeline:
    st.subheader("Two-stage pipeline")

    with st.container(border=True):
        st.markdown("### :material/table_chart: Stage 1 · Process — raw .D folders → peak table")
        st.markdown(
            "**Input:** Agilent .D injection folders (HPLC uses UV/DAD; GC-MS uses MS detector)  \n"
            "**Output:** `peak_results.csv`, chromatogram overlay, chromatogram gallery"
        )
        st.markdown(
            """
1. **Load .D folders** — the pipeline discovers all injection folders that match the sample-name
   pattern, plus any standard folders (GC-MS) or a blank injection (HPLC).
2. **Extract signal** — for HPLC, the absorbance trace at your chosen wavelength (nm) is extracted
   from the DAD detector. For GC-MS, the extracted-ion chromatogram (EIC) at the quantifier m/z
   is used (or TIC / FID, configurable).
3. **Blank subtraction** *(HPLC only)* — if a blank injection is specified, its baseline is
   subtracted from every sample before peak detection.
4. **Peak detection** — `find_peaks()` identifies local maxima above configurable height, prominence,
   and width thresholds.
5. **Peak deconvolution** *(HPLC only)* — overlapping peaks are deconvolved using Gaussian and/or
   FraserSuzuki model fitting (MOCCA2 library). The best-fit model with R² above the minimum
   threshold is accepted; otherwise a trapezoidal integral is used as fallback.
6. **Export** — a peak table CSV is written with RT, area, and injection metadata for every
   detected peak. Chromatogram plots are generated.
"""
        )

    with st.container(border=True):
        st.markdown("### :material/analytics: Stage 2 · Analyze — peak table → concentrations + dashboard")
        st.markdown(
            "**Input:** peak table from Stage 1, `compounds.csv` (RT windows), `standard.csv` (calibration)  \n"
            "**Output:** `consolidated_peaks.csv`, interactive Bokeh dashboard"
        )
        st.markdown(
            """
1. **RT-window assignment** — each peak is assigned to the compound whose RT window it falls within.
   Peaks outside all windows are labelled "unknown" (and excluded from plots if `exclude_unknown` is on).
2. **Calibration** — for each compound, a linear regression is fitted to the `(area, concentration)`
   pairs in `standard.csv`. This gives `conc = area / slope` (optionally with an intercept term).
   Negative concentrations can be clamped to zero.
3. **Quantification** — every sample peak area is converted to µM using the calibration curve.
   Compounds with zero area are reported as 0 µM (rather than the intercept artefact).
4. **Replicate statistics** — mean and standard deviation are calculated across replicates for each
   (strain, time, compound) group. Groups with CV% above the warning threshold are flagged.
5. **Dashboard generation** — a Bokeh HTML dashboard is written with:
   - **Time-series line plots** — mean concentration vs. time per strain (one panel per compound)
   - **Bar charts** — mean ± SD across strains at selected time points
   - **Calibration curve plots** — fitted line + data points, R² displayed
"""
        )

    if True:
        st.divider()
        st.subheader("Combined HPLC + GC-MS dashboard")
        st.markdown(
            "When both modalities are active and Stage 2 has been run, a `combined_analysis/` "
            "folder is created with a single Bokeh dashboard showing **all compounds from both "
            "instruments** on one page. Useful for comparing HPLC and GC-MS results for the same "
            "strains and time points."
        )


# ── Parameters ────────────────────────────────────────────────────────────────
with tab_params:
    st.subheader("Key parameters explained")
    st.caption(
        "All of these live in `hplc_config.yaml` and can be edited in the **Parameters** page. "
        "Click **Apply changes** to save; then re-run the pipeline to see the effect."
    )

    with st.expander("Detection wavelength (nm)", icon=":material/radio_button_checked:"):
        st.markdown(
            "The UV wavelength extracted from the DAD detector for HPLC peak integration. "
            "Choose the wavelength where your target compounds have strong absorbance "
            "(e.g., 262 nm for phenylpropanoids). Check the UV spectrum of your standards — "
            "a wavelength near the absorbance maximum gives the best signal-to-noise ratio. "
            "Using a wavelength where the compounds barely absorb will result in noisy, "
            "poorly integrated peaks."
        )

    with st.expander("Blank injection", icon=":material/water:"):
        st.markdown(
            "Set `blank_folder_name` to the .D folder name of a blank run (e.g., `blank.D` or "
            "`0, media, blank.D`). The blank's chromatogram is subtracted from every sample "
            "before peak detection, removing baseline drift, solvent peaks, and matrix "
            "background. Omit (leave blank) if you have no blank injection."
        )

    with st.expander("Retention-time windows (`compounds.csv`)", icon=":material/timeline:"):
        st.markdown(
            "Each compound needs an RT window [RT_low, RT_high] in minutes. "
            "The window should:"
        )
        st.markdown(
            "- **Contain the peak apex** for all samples (allow for slight RT shifts between injections)\n"
            "- **Not overlap** with adjacent compound windows\n"
            "- Be as **narrow as possible** while still capturing the peak, to avoid assigning "
            "neighbouring peaks to the wrong compound"
        )
        st.markdown(
            "Typical window width: ±0.1–0.3 min around the expected RT. "
            "Run Stage 1 first, then open `results/chromatogram_gallery.html` to measure exact RTs."
        )

    with st.expander("Calibration (`standard.csv`)", icon=":material/show_chart:"):
        st.markdown(
            "The pipeline builds a linear calibration curve per compound from your standard data. "
            "**Requirements:**"
        )
        st.markdown(
            "- At least **3 concentration points** per compound (5+ recommended for a reliable fit)\n"
            "- Concentration range should **bracket** your expected sample concentrations\n"
            "- Integrate the standard peaks from your standard injections and enter "
            "the `Area_Integral` values manually, or run the pipeline on a dedicated "
            "standards-only experiment folder"
        )
        st.markdown(
            "The R² of each calibration fit is shown in the Results dashboard. "
            "A low R² (< 0.99) suggests outlier points, non-linearity, or a wrong RT window."
        )

    with st.expander("Peak detection parameters", icon=":material/tune:"):
        st.markdown(
            "These control MOCCA2's `find_peaks()` call. Leave all four blank to use "
            "MOCCA2's automatic defaults, which work well for most experiments."
        )
        col1, col2 = st.columns(2)
        with col1:
            st.markdown(
                "**min_height** — minimum peak height (mAU). "
                "Raise this to suppress noise peaks in noisy chromatograms."
            )
            st.markdown(
                "**min_prominence** — minimum height of the peak above its surrounding baseline. "
                "Useful for suppressing shoulders that are detected as separate peaks."
            )
        with col2:
            st.markdown(
                "**min_width** — minimum peak width in data points. "
                "Helps filter out injection spikes."
            )
            st.markdown(
                "**distance** — minimum spacing between two peaks (data points). "
                "Increase if closely spaced peaks are merged incorrectly."
            )

    with st.expander("Plot customisation", icon=":material/bar_chart:"):
        col_a, col_b = st.columns(2)
        with col_a:
            st.markdown("**Strains to plot** (`plot_strains`)")
            st.markdown(
                "Leave empty to show all strains. Enter a subset to focus the dashboard on "
                "specific strains — e.g., `['media', 's1', 's10', 's11']`. "
                "Other strains are excluded from bar charts and time-series."
            )
            st.markdown("**Bar-chart time points** (`bar_time_points`)")
            st.markdown(
                "Leave empty to include all time points. Enter a list — e.g., `[0, 24, 50]` — "
                "to restrict bar charts to those hours. Useful when you have many time points "
                "but only want to compare specific ones."
            )
        with col_b:
            st.markdown("**Colour palette** (`palette`)")
            st.markdown(
                "One hex colour per line; strains cycle through it in the order they appear "
                "in the plot. The default palette has 8 colours. "
                "Add more if you have more than 8 strains."
            )
            st.markdown("**Strain order** (`strain_order`)")
            st.markdown(
                "Controls which strain gets which colour. "
                "List strain names in the order you want them mapped to the palette — "
                "the first strain gets the first colour, and so on. "
                "Leave blank for alphabetical order."
            )
        st.markdown("**Grid columns** (`n_cols`)")
        st.markdown(
            "Number of compound panels per row in the Bokeh dashboard grid. "
            "2 is a good default; use 3 or 4 if you have many compounds and a wide monitor."
        )

    with st.expander("GC-MS: quantification channel", icon=":material/biotech:"):
        st.markdown(
            "Controls which signal is integrated for GC-MS quantification:"
        )
        st.markdown(
            "- **EIC** (extracted-ion chromatogram) — integrates only the quantifier m/z ion. "
            "Most selective; best for complex matrices. **Recommended.**\n"
            "- **TIC** (total ion current) — sum of all ions. Higher signal but less selective.\n"
            "- **FID** (flame-ionisation detector) — if your instrument has an FID channel."
        )

    with st.expander("GC-MS: ion-ratio confirmation", icon=":material/verified:"):
        st.markdown(
            "Qualifier ions are secondary m/z fragments that should appear at a predictable "
            "ratio relative to the quantifier ion. If `require_ion_ratio_pass` is on, any peak "
            "where the qualifier ratio is outside the expected range (± `ion_ratio_tol`) is "
            "reported as 0 µM rather than the fitted value. "
            "This provides an extra identity check but requires well-tuned expected ratios "
            "in `gc_compounds.csv`."
        )


# ── Results ──────────────────────────────────────────────────────────────────
with tab_results:
    st.subheader("What the pipeline generates")

    st.markdown(
        "After a successful run, the **Results** section appears in the sidebar with links to "
        "interactive HTML dashboards. All output files are also accessible directly in the "
        "experiment folder."
    )

    col_hplc, col_gc = st.columns(2)

    with col_hplc:
        with st.container(border=True):
            st.markdown("### :material/water_drop: HPLC outputs")
            st.markdown("**`results/`** — Stage 1")
            st.markdown(
                "- `peak_results.csv` — every detected peak: RT, area, width, injection name\n"
                "- `sample_summary.csv` — one row per injection: total peaks, max area\n"
                "- `chromatogram_gallery.html` — individual chromatogram per injection with "
                "peak annotations; useful for checking peak quality\n"
                "- `chromatogram_overlay_interactive.html` — all chromatograms overlaid; "
                "hover to identify injections"
            )
            st.markdown("**`analysis/`** — Stage 2")
            st.markdown(
                "- `consolidated_peaks.csv` — concentration (µM) for every compound in every "
                "sample; one row per (injection, compound)\n"
                "- `analysis_plots.html` — main **Bokeh dashboard** (see below)"
            )

    with col_gc:
        with st.container(border=True):
            st.markdown("### :material/biotech: GC-MS outputs")
            st.markdown("**`gc_results/`** — Stage 1")
            st.markdown(
                "- `gc_peak_results.csv` — peak table\n"
                "- `chromatogram_gallery.html` — individual TIC/EIC traces\n"
                "- `gc_tic_overlay_interactive.html` — overlaid TIC chromatograms"
            )
            st.markdown("**`gc_analysis/`** — Stage 2")
            st.markdown(
                "- `gc_consolidated_peaks.csv` — concentrations per sample\n"
                "- `analysis_plots.html` — GC-MS Bokeh dashboard\n"
                "- `ion_ratio_check.csv` — qualifier-ratio pass/fail for each peak"
            )

    st.divider()
    with st.container(border=True):
        st.markdown("### :material/merge: Combined dashboard (`combined_analysis/`)")
        st.markdown(
            "When both HPLC and GC-MS are active, a single `analysis_plots.html` shows all "
            "compounds from both instruments together — useful for cross-modal comparison of "
            "the same strains and time points."
        )

    st.divider()
    st.subheader("The Bokeh dashboard — what's in it")
    st.markdown(
        "Open `analysis_plots.html` in your browser (or use the **Open in browser** button on "
        "the Results page) to explore the interactive dashboard. It contains:"
    )

    with st.expander("Time-series line plots", icon=":material/timeline:"):
        st.markdown(
            "One panel per compound. X-axis = time (h), Y-axis = mean concentration (µM). "
            "Each strain is a separate line with error bars (± SD across replicates). "
            "Hover over a data point to see the exact value. "
            "Click the strain name in the legend to hide/show it."
        )

    with st.expander("Bar charts", icon=":material/bar_chart:"):
        st.markdown(
            "One panel per compound. Shows mean ± SD concentration for each strain at the "
            "selected time points (`bar_time_points`). Strains are grouped side by side. "
            "Individual replicate values are overlaid as dots. "
            "Useful for comparing strains at a specific time point."
        )

    with st.expander("Calibration curve plots", icon=":material/show_chart:"):
        st.markdown(
            "One panel per compound. Shows the standard data points and the fitted linear "
            "regression line. R² is displayed. "
            "Check these to verify that the calibration is sensible and that no outlier "
            "points are distorting the fit."
        )

    with st.expander("Chromatogram gallery & overlay", icon=":material/photo_library:"):
        st.markdown(
            "The **gallery** (`chromatogram_gallery.html`) shows one chromatogram per injection, "
            "annotated with compound RT windows and detected peak areas. "
            "Use this to check peak quality, verify RT assignments, and spot any "
            "unusual injections before trusting the quantification."
        )
        st.markdown(
            "The **overlay** (`chromatogram_overlay_interactive.html`) puts all chromatograms "
            "on one plot. Hover to identify traces. "
            "Useful for checking RT reproducibility across injections."
        )

    st.divider()
    st.subheader("Interpreting the results")
    st.markdown(
        "- **CV% warnings** in the run log indicate replicate groups with high variability "
        "(default threshold: 15%). High CV% may reflect biological variability, pipetting "
        "errors, or peak integration problems — check the chromatogram gallery for those samples.\n"
        "- **Negative concentrations** can arise from calibration intercepts or baseline noise. "
        "Enable *Clamp negative conc. to 0* in Parameters to report them as zero.\n"
        "- **Zero-area compounds** (compound RT window detected but no peak above threshold) "
        "are reported as 0 µM when *Zero area → 0 µM* is on, rather than using the "
        "calibration intercept as a spurious non-zero value."
    )
